In [8]:
import numpy as np
from hmmlearn import hmm

In [9]:
dic = {'a': 0, 'b': 1}

file = open("final1.txt", "r") 
data = file.read() 
letters = data.replace('\n', ' ').split(" ")
train_num = np.array([dic[i] for i in letters])
file.close()

file = open("first.txt", "r") 
data = file.read() 
letters = data.replace('\n', ' ').split(" ")
val_a = np.array([dic[i] for i in letters])
file.close()

file = open("second.txt", "r") 
data = file.read() 
letters = data.replace('\n', ' ').split(" ")
val_b = np.array([dic[i] for i in letters])
file.close()

file = open("third.txt", "r") 
data = file.read() 
letters = data.replace('\n', ' ').split(" ")
val_c = np.array([dic[i] for i in letters])
file.close()

file = open("fourth.txt", "r") 
data = file.read() 
letters = data.replace('\n', ' ').split(" ")
val_d = np.array([dic[i] for i in letters])
file.close()

In [22]:
print(val_a.reshape(-1,1))
print(val_b)
print(val_c)
print(val_d)

[[0]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
[0 1 1 ... 0 0 1]
[0 1 0 ... 1 1 0]
[0 0 0 ... 1 0 0]


In [11]:
train_ratio = 0.5
train_size = int(len(train_num) * train_ratio)
train_data = train_num[:train_size]
test_data = train_num[train_size:]

### Hidden Markov

In [12]:
def submit(method, pred, val):
    correct_guesses = np.sum(pred == val)
    incorrect_guesses = np.sum(pred != val)
    if len(pred) != len(val):
        print("Invalid submission")
        return
    correct = 0
    fails = 0
    counter = 0
    for i in range(len(pred)):
        if val[i] == pred[i]:
            correct += 1
            counter = 0
        else:
            counter += 1
            if counter >= 5:
                counter = 0
                fails += 1

    print(f"{method}: Percent - {correct/(correct+fails)*100}%, Correct - {correct}, Fails - {fails}")
    print(f"Correct Guesses: {correct_guesses}, Incorrect Guesses: {incorrect_guesses}")

In [19]:
model = hmm.CategoricalHMM(n_components=2, random_state=1851927920)
dat_reshape = np.reshape(train_num[:20200], (2,-1))
for idx, dat in enumerate(dat_reshape):
    if idx == 0:
        model.fit(dat.reshape(-1, 1))
    else:
        pred = model.predict(dat.reshape(-1, 1))
        submit("HMM" + str(idx), pred, dat_reshape[0])
        

HMM1: Percent - 96.22038360285822%, Correct - 5117, Fails - 201
Correct Guesses: 5117, Incorrect Guesses: 4983


1851927920

In [39]:
model = hmm.CategoricalHMM(n_components=2, random_state=1851927920)
model.fit(val_a.reshape(-1, 1))

test_predict = model.predict(val_a.reshape(-1, 1))
test_predict = ~test_predict.astype(bool)

correct_guesses = np.sum(val_a == val_a)
incorrect_guesses = np.sum(val_a != val_a)
print(correct_guesses / len(val_a))
print(incorrect_guesses / len(val_a))

1.0
0.0


In [40]:
def get_accuracy(model, data):
    test_predict = model.predict(data.reshape(-1, 1))
    test_predict = ~test_predict.astype(bool)

    correct_guesses = np.sum(test_predict == data)
    incorrect_guesses = np.sum(test_predict != data)
    return correct_guesses / len(data), incorrect_guesses / len(data)

for dat in [val_a, val_b, val_c, val_d]:
    print(get_accuracy(model, dat))

(1.0, 0.0)
(1.0, 0.0)
(1.0, 0.0)
(1.0, 0.0)


In [21]:
for dat in [val_a, val_b, val_c, val_d]:
    submit("HMM", ~model.predict(dat.reshape(-1, 1)).astype('bool'), dat.astype('bool'))

HMM: Percent - 100.0%, Correct - 3469, Fails - 0
Correct Guesses: 3469, Incorrect Guesses: 282
HMM: Percent - 100.0%, Correct - 4617, Fails - 0
Correct Guesses: 4617, Incorrect Guesses: 333
HMM: Percent - 100.0%, Correct - 7836, Fails - 0
Correct Guesses: 7836, Incorrect Guesses: 496
HMM: Percent - 100.0%, Correct - 2990, Fails - 0
Correct Guesses: 2990, Incorrect Guesses: 174
